/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* dlmb_cntlr memory will not be tested since application resides in the same memory */
	{
		"sram",
		"xps_mch_emc",
		0x9af00000,
		1048576,
	},
	{
		"ddr2_sdram",
		"mpmc",
		0xb0000000,
		268435456,
	},
};

int n_memory_ranges = 2;
